config/routes.rb
Rails.application.routes.draw do
  # páginas
  root 'paginas#inicio'
  get   '/carrito',     to: 'paginas#carro',              as: 'carrito'
  get   'enviar', to: 'paginas#enviar_saludo'

  # sesiones
  post    '/sesiones',  to: 'sesiones#iniciar_sesion',  as: 'iniciar_sesion'
  delete  '/sesiones',  to: 'sesiones#cerrar_sesion',  as: 'cerrar_sesion'

  # carros
  post    'carros/:id_producto',          to: 'carros#agregar_producto',            as: 'agregar_producto'
  put     'carros/:id_producto/cantidad', to: 'carros#aumentar_cantidad_producto',  as: 'aumentar_producto'
  delete  'carros/:id_producto',          to: 'carros#eliminar_producto',           as: 'eliminar_producto'
  delete  'carros/:id_producto/cantidad', to: 'carros#disminuir_cantidad_producto', as: 'disminuir_producto'

  # pedidos cliente
  get   'pedidos',        to: 'pedidos#crear',    as: 'nuevo_pedido'
  get   'pagar',          to: 'pedidos#pagar',    as: 'pagar'  
  post  'pedidos',        to: 'pedidos#guardar',  as: 'crear_pedido_cliente'

  # admin
  namespace :admin do

    # categorias
    get 'categorias',             to: 'categorias#listar',  as: 'categorias'
    get 'categorias/crear',       to: 'categorias#crear',   as: 'nueva_categoria'
    get 'categorias/:id',         to: 'categorias#mostrar', as: 'categoria'
    get 'categorias/:id/editar',  to: 'categorias#editar',  as: 'editar_categoria'

    post    'categorias',     to: 'categorias#guardar'
    put     'categorias/:id', to: 'categorias#actualizar'
    patch   'categorias/:id', to: 'categorias#actualizar'
    delete  'categorias/:id', to: 'categorias#eliminar'

    # detinos
    get 'destinos',             to: 'destinos#listar',  as: 'destinos'
    get 'destinos/crear',       to: 'destinos#crear',   as: 'nuevo_destino'
    get 'destinos/:id',         to: 'destinos#mostrar', as: 'destino'
    get 'destinos/:id/editar',  to: 'destinos#editar',  as: 'editar_destino'

    post    'destinos',     to: 'destinos#guardar'
    put     'destinos/:id', to: 'destinos#actualizar'
    patch   'destinos/:id', to: 'destinos#actualizar'
    delete  'destinos/:id', to: 'destinos#eliminar'

    # productos
    get 'productos',              to: 'productos#listar',   as: 'productos'
    get 'productos/crear',        to: 'productos#crear',    as: 'nuevo_producto'
    get 'productos/:id',          to: 'productos#mostrar',  as: 'producto'
    get 'productos/:id/editar',   to: 'productos#editar',   as: 'editar_producto'

    post    'productos',                          to: 'productos#guardar'
    put     'productos/:id',                      to: 'productos#actualizar'
    patch   'productos/:id',                      to: 'productos#actualizar'
    # delete  'productos/:id',                      to: 'productos#eliminar'
    
    delete  'productos/:id/imagenes/:id_imagen',  to: 'productos#eliminar_foto',  as: 'eliminar_foto'

    # pedidos
    get '/',                  to: 'pedidos#listar',   as: 'pedidos'
    # get 'pedidos/crear',      to: 'pedidos#crear',    as: 'nuevo_pedido'
    get 'pedidos/:id',        to: 'pedidos#mostrar',  as: 'pedido'
    get 'pedidos/:id/editar', to: 'pedidos#editar',   as: 'editar_pedido'

    post    'pedidos',      to: 'pedidos#crear',      as: 'pedidos_helper_pedidos_formularios'
    put     'pedidos/:id',  to: 'pedidos#actualizar'
    patch   'pedidos/:id',  to: 'pedidos#actualizar', as: 'pedidos_helper_pedidos_formulario'
    delete  'pedidos/:id',  to: 'pedidos#eliminar'

    get     'pedidos/:id/productos',                        to: 'pedidos#agregar_producto',             as: 'agregar_producto_pedido'
    post    'pedidos/:id/productos/:id_producto',           to: 'pedidos#guardar_producto',             as: 'guardar_producto_pedido'
    put     'pedidos/:id/productos/:id_producto',           to: 'pedidos#aumentar_cantidad_producto',   as: 'aumentar_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto',           to: 'pedidos#disminuir_cantidad_producto',  as: 'disminuir_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto/eliminar',  to: 'pedidos#eliminar_producto',            as: 'eliminar_producto_pedido'
  end
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :destino, optional: true
  belongs_to :datos_envio, optional: true
  belongs_to :estados_pedido

  has_one :venta
  has_many :detalles_pedidos, -> { order(id: :asc) }, dependent: :destroy
  has_many :productos, through: :detalles_pedidos


end

app/controllers/admin/pedidos_controller.rb
class Admin::PedidosController < Admin::AdminController
    
    include Admin::PedidosHelper

    before_action :asignar_pedido, except: [:listar, :crear, :guardar]

    # GET
    def listar
        @pedidos = Pedido.select(:id, :codigo, :total, :created_at, :estados_pedido_id).order(created_at: :desc)
    end

    # GET
    def mostrar
        
    end

    # GET
    def agregar_producto
        @todos_los_productos = Producto.select(:id, :nombre, :precio, :estados_producto_id).order(nombre: :asc).where("estados_producto_id = 1 and cantidad > 0")
    end

    # GET
    def editar
        @datos_pedido = PedidosFormulario.new
        @datos_pedido.id            = @pedido.id
        @datos_pedido.nombre        = @pedido.datos_envio.nombre
        @datos_pedido.correo        = @pedido.datos_envio.correo
        @datos_pedido.telefono      = @pedido.datos_envio.telefono
        @datos_pedido.direccion     = @pedido.datos_envio.direccion
        @datos_pedido.destino_id    = @pedido.destino.id            
        @datos_pedido.estado_id     = @pedido.estados_pedido.id
        @estados    = EstadosPedido.select(:id, :estado).order(estado: :asc)
        @destinos   = Destino.select(:id, :nombre).order(nombre: :asc)
        @productos = @pedido.detalles_pedidos # lista de productos
    end

    # POST
    def crear
        @pedido = Pedido.new
        @pedido.codigo          = SecureRandom.hex(4).upcase
        @pedido.total           = 0
        @pedido.estados_pedido  = EstadosPedido.find_by(estado: 'solicitado')
        @pedido.destino         = Destino.find_by(nombre: "Sin destino")
        @pedido.datos_envio     = DatosEnvio.create(
                                        nombre:     'ingrese nombre',
                                        telefono:   'ingrese teléfono',
                                        direccion:  'ingrese dirección',
                                        correo:     'ingrese correo'
                                    )
        @pedido.save
        
        redirect_to admin_editar_pedido_path(@pedido)
    end


    # POST
    def guardar_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        if detalle_pedido
            detalle_pedido.cantidad += 1
        else
            detalle_pedido = DetallesPedido.new(
                pedido: @pedido,
                producto_id: params[:id_producto],
                cantidad: 1
            )
        end
        detalle_pedido.save
        
        redirect_to action: :editar
    end

    # PUT/PATCH
    def actualizar
        @datos_pedido = PedidosFormulario.new(params_pedidos)
        if @datos_pedido.valid?
            @pedido.datos_envio.nombre = @datos_pedido.nombre
            @pedido.datos_envio.correo = @datos_pedido.correo
            @pedido.datos_envio.telefono = @datos_pedido.telefono
            @pedido.datos_envio.direccion = @datos_pedido.direccion
            
            @pedido.destino = Destino.find(@datos_pedido.destino_id)
            @pedido.estados_pedido = EstadosPedido.find(@datos_pedido.estado_id)        # línea nueva 🌟

            if @pedido.datos_envio.save and @pedido.save
                redirect_to action: :mostrar
            else                
                @destinos = Destino.select(:id, :nombre).order(nombre: :asc)
                @estados    = EstadosPedido.select(:id, :estado).order(estado: :asc)    # línea nueva 🌟
                render :editar
            end
        else
            @destinos = Destino.select(:id, :nombre).order(nombre: :asc)
            @estados    = EstadosPedido.select(:id, :estado).order(estado: :asc)        # línea nueva 🌟
            render :editar
        end
    end

    # DELETE
    def eliminar
        #TODO analizar si vamos a elimnar el pedido o vamos a cambiar de estado
    end

    # PUT pedidos/:id/productos/:id_producto
    def aumentar_cantidad_producto
        @detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        @detalle_pedido.cantidad += 1
        @detalle_pedido.save

        redirect_to :editar
        # respond_to do |format|
        #     format.js
        #     # format.json { render json: detalle_pedido.producto }
        # end
    end
    
    # DELETE pedidos/:id/productos/:id_producto
    def disminuir_cantidad_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        if detalle_pedido.cantidad - 1 <= 0
            detalle_pedido.destroy
        else
            detalle_pedido.cantidad -= 1
            detalle_pedido.save
        end

        redirect_to action: :editar
        # respond_to do |format|
        #     format.json { render json: {id: detalle_pedido.producto.id, cantidad: detalle_pedido.cantidad} }
        # end
    end

    # DELETE pedidos/:id/productos/:id_producto/eliminar
    def eliminar_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        detalle_pedido.destroy

        redirect_to action: :editar
    end

    private 
    def params_pedidos
        params.require(:admin_pedidos_helper_pedidos_formulario)
        .permit(:nombre, :correo, :telefono, :direccion, :destino_id, :estado_id)       # agregamos :estado_id 🌟
    end

    def asignar_pedido
        
        @pedido = Pedido.find(params[:id])

    rescue ActiveRecord::RecordNotFound

        flash[:errors] = "Pedido #{params[:id]} no encontrado"
        redirect_to action: :listar
    end

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController

    include PedidosHelper
    layout 'paginas'
    before_action :validar_carro
    before_action :validar_productos_carrito, only: :crear
    
    # GET
    def crear
        @datos_formulario = DatosEnvioFormulario.new
        consultar_destinos  # 🚧
    end

    # GET
    def pagar

    end

    # POST
    def guardar
        @datos_formulario = DatosEnvioFormulario.new(params_datos_formulario)
        if @datos_formulario.valid?
            @datos_envio = crear_datos_envio(@datos_formulario)
            @pedido = definir_pedido(@carro.total, @datos_formulario, @datos_envio)
            if @pedido.save
                migrar_productos(@carro, @pedido)
                enviar_correo       # 📬
                eliminar_carrito    # 🛒
                render :pagar       # 💰
            else
                consultar_destinos  # 🚧
                render :crear
            end
        else
            consultar_destinos  # 🚧
            render :crear
        end
    end

    private

    def params_datos_formulario
        params.require(:pedidos_helper_datos_envio_formulario).permit(:nombre, :correo, :direccion, :telefono, :destino_id)
    end

    def enviar_correo
        ClienteMailer.with(datos_envio_correo: @datos_envio, pedido_correo: @pedido).enviar_correo_pedido.deliver_later
    end

    def eliminar_carrito
        session[:carro_id] = nil
        @carro.destroy
    end

    def consultar_destinos
        @destinos = Destino.select(:id, :nombre).order(nombre: :asc).select{ |d| d.nombre != "Sin destino" }
    end

    def validar_productos_carrito
        if @carro.productos.count.zero?
            redirect_to root_path
        end
    end

end

app/helpers/admin/pedidos_helper.rb
# frozen_string_literal: true

module Admin
  module PedidosHelper
    # Modelo para construir la vista del pedido
    class PedidosFormulario
      include ActiveModel::Model

      attr_accessor(:id, :nombre, :correo, :direccion, :telefono, :destino_id, :estado_id)

      validates(:nombre, presence: true)
      validates(:direccion, presence: true)
      validates(:correo, presence: true)
      validates(:telefono, presence: true)
      validates(:destino_id, presence: true)

      def persisted?
        id != nil
      end
    end
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
    class DatosEnvioFormulario
        include ActiveModel::Model

        attr_accessor :nombre
        attr_accessor :correo
        attr_accessor :direccion
        attr_accessor :telefono
        attr_accessor :destino_id

        validates(:nombre, presence: true)
        validates(:direccion, presence: true)
        validates(:correo, presence: true)
        validates(:telefono, presence: true)
        validates(:destino_id, presence: true)
    end

    def crear_datos_envio(datos_formulario)
        DatosEnvio.create(
            nombre: datos_formulario.nombre,
            direccion: datos_formulario.direccion,
            telefono: datos_formulario.telefono,
            correo: datos_formulario.correo
        )
    end

    def definir_pedido(total, datos_formulario, datos_envio)
        Pedido.new(
            codigo: SecureRandom.hex(4).upcase,
            total: total,
            destino_id: datos_formulario.destino_id,
            estados_pedido: EstadosPedido.find_by(estado: 'solicitado'),
            datos_envio: datos_envio
        )
    end

    def migrar_productos(carro, pedido)
        carro.carros_contenidos.each do |contenido|
            DetallesPedido.create(
                pedido: pedido,
                producto: contenido.producto,
                cantidad: contenido.cantidad
            )
        end
    end
end

app/views/admin/pedidos/_formulario_datos_envio.html.erb
<%= form_with(model: datos_pedido) do |formulario| %>

    <div class="row mt-2">
        <div class="col">
            <div class="alert alert-primary" role="alert">
                <%= formulario.label :estado_id, class: 'form-label' %>
                <%= formulario.select(:estado_id,
                    options_from_collection_for_select(estados, :id, :estado, datos_pedido.estado_id),
                    {},
                    {class: 'form-select'}) %>
                <% if datos_pedido.errors[:estado_id].any? %>
                    <div style="color: red">
                        <%= datos_pedido.errors[:estado_id].first %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>    

    <div class="row mt-4 justify-content-between">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        Datos envío
                    </h4>
                    <!-- DATOS DE ENVÍO -->
                    <div class="row">
                        <div class="col-12">
                            <%= formulario.label :nombre, class: 'form-label' %>
                            <%= formulario.text_field :nombre, class: 'form-control' %>
                            <% if datos_pedido.errors[:nombre].any? %>
                                <div style="color: red">
                                    <%= datos_pedido.errors[:nombre].first %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <%= formulario.label :correo, class: 'form-label' %>
                            <%= formulario.text_field :correo, class: 'form-control' %>
                            <% if datos_pedido.errors[:correo].any? %>
                                <div style="color: red">
                                    <%= datos_pedido.errors[:correo].first %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <%= formulario.label :telefono, class: 'form-label' %>
                            <%= formulario.text_field :telefono, class: 'form-control' %>
                            <% if datos_pedido.errors[:telefono].any? %>
                                <div style="color: red">
                                    <%= datos_pedido.errors[:telefono].first %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <%= formulario.label :direccion, class: 'form-label' %>
                            <%= formulario.text_field :direccion, class: 'form-control' %>
                            <% if datos_pedido.errors[:direccion].any? %>
                                <div style="color: red">
                                    <%= datos_pedido.errors[:direccion].first %>
                                </div>
                            <% end %>                        
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <%= formulario.label :destino_id, class: 'form-label' %>
                            <%= formulario.select(:destino_id,
                                options_from_collection_for_select(destinos, :id, :nombre, datos_pedido.destino_id),
                                {include_blank: 'Elige un destino'},
                                {class: 'form-select'}) %>
                            <% if datos_pedido.errors[:destino_id].any? %>
                                <div style="color: red">
                                    <%= datos_pedido.errors[:destino_id].first %>
                                </div>
                            <% end %>
                        </div>
                    </div> <!-- Destinos 🗺 -->
                    
                    <div class="row mt-3">
                        <div class="col-12">
                            <%= formulario.submit class: 'btn btn-primary text-white' %>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- Formulario 🏂 -->
    </div>
<% end %>

app/views/admin/pedidos/_listar_productos.html.erb
<div class="card mt-2">
    <div class="card-body">
        <div class="row justify-content-between">
            <div class="col-4">
                <h4 class="card-title">
                    Productos
                </h4>
            </div>
            <div class="col-4 text-end">
                <%= link_to "Agregar", admin_agregar_producto_pedido_path(pedido), class: 'btn btn-primary' %>
            </div>
        </div>
        
        <div class="row  text-center mt-5">
            <div class="col-12">
                <div class="row">
                    <div class="col-2">
                        <strong>
                            Imágen
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Nombre
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Precio
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Cantidad
                        </strong>
                    </div>
                    <div class="col text-end">
                        <strong>
                            Eliminar
                        </strong>
                    </div>
                </div>
                <% productos.each do |detalle| %>
                    <div class="row mt-5">
                        <div class="col-2">
                            <%= image_tag detalle.producto.imagenes.first, class: 'w-100' %>                
                        </div>
                        <div class="col">
                            <%= detalle.producto.nombre %>                
                        </div>
                        <div class="col">
                            <%= detalle.producto.precio %>                
                        </div>
                        <div class="col">
                            <%= link_to "-", admin_disminuir_producto_pedido_path(detalle.pedido_id, detalle.producto_id), method: :delete, remote: true, class: 'btn btn-secondary' %>
                            
                            <span id="cantidad-producto-<%=detalle.producto.id%>"> <%= detalle.cantidad %>                </span>
                            
                            <%= link_to "+", admin_aumentar_producto_pedido_path(detalle.pedido_id, detalle.producto_id), method: :put, remote: true, class: 'btn btn-secondary' %>
                        </div>
                        <div class="col text-end">
                            <%= link_to admin_eliminar_producto_pedido_path(detalle.pedido_id, detalle.producto_id), method: :delete, class: 'btn btn-danger' do %>
                                <i class="bi bi-trash"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>
                <!-- MOSTRAR LOS PRODUCTOS -->
            </div>
        </div>
    </div>
</div>

app/views/admin/pedidos/agregar_producto.html.erb
<div class="row">
    <div class="col-10">
        <h2>
            AGREGAR PRODUCTOS AL PEDIDO <%= @pedido.codigo %> 📦
        </h2>    
    </div>
    <div class="col-2 text-end">
        <%= link_to "Cancelar", admin_editar_pedido_path(@pedido), class: 'btn btn-secondary' %>
    </div>
</div>

<div class="row justify-content-start">
        <% @todos_los_productos.each do |producto| %>
            <div class="col-lg-3 col-10 mt-3">
                <div class="card">
                <%= image_tag producto.imagenes.first, class: 'card-img-top' %>
                    <div class="card-body">
                        <h5 class="card-title"><%= producto.nombre %></h5>
                        <%= producto.precio.to_s[0..-3] %> CLP
                    </div>
                    <%= link_to 'Agregar al pedido', admin_guardar_producto_pedido_path(@pedido, producto), class: 'btn btn-primary', method: :post, remote: true %>
                </div>
            </div>    
        <% end %>
</div>

app/views/admin/pedidos/aumentar_cantidad_producto.js.erb
const spanPrueba = document.getElementById("cantidad-producto-" + <%= j @detalle_pedido.producto_id %>)
spanPrueba.innerHTML = <%= j @detalle_pedido.cantidad %>

app/views/admin/pedidos/editar.html.erb
<div class="row">
    <div class="col-10">
        <h2>
            EDITAR PEDIDO <%= @pedido.codigo %> 📦
        </h2>    
    </div>
    <div class="col-2 text-end">
        <%= link_to "Volver", admin_pedido_path(@pedido), class: 'btn btn-secondary' %>
    </div>
</div>

<div class="row mt-3 justify-content-end">
    <div class="col">
        <div class="card">
            <div class="card-body text-center">
                <h6>
                    <strong>
                        TOTAL:
                    </strong>
                </h6>
                <p>
                    <!-- TODO: AGREAR TOTAL CALCULADO -->
                    <%= @pedido.total %> 💵💵
                </p>
            </div>
        </div>
    </div> <!-- TOTAL 📎 -->
</div>

<div class="row">
    <div class="col-lg-4">
        <%= render 'formulario_datos_envio', datos_pedido: @datos_pedido, destinos: @destinos, estados: @estados  %>
    </div>
    <div class="col-lg-8">
        <%= render 'listar_productos', productos: @productos, pedido: @pedido %>
    </div>
</div>

app/views/admin/pedidos/listar.html.erb
<div class="row">
    <div class="col">
        <h2>Pedidos</h2>
    </div>
    <div class="col text-end">
        <%= link_to admin_pedidos_helper_pedidos_formularios_path, 
                    class: "btn btn-primary text-white", 
                    method: :post,
                    data: { confirm: '¿Quieres crear un nuevo pedido?' }  do %>
            <i class="bi bi-plus-circle"></i>
            Crear pedido
        <% end %>
    </div>
</div>

<% if flash[:errors] %>
    <div class="alert alert-warning mt-3" role="alert">
        <%= flash[:errors] %>
    </div>
<% end %>

<div class="row mb-4 mt-4">
    <div class="col text-muted">Código</div>
    <div class="col text-muted">Estado</div>
    <div class="col text-muted">Total</div>
    <div class="col text-muted">Fecha</div>
    <div class="col text-muted"></div>
</div>
<% @pedidos.each do |pedido| %>
    <div class="row fila">
        <div class="col"> <strong> <%= pedido.codigo %> </strong> </div>
        <div class="col"> <%= pedido.estados_pedido.estado %> </div>
        <div class="col"> <%= pedido.total %> </div>
        <div class="col"> <%= pedido.created_at.strftime("%d/%m/%Y") %> </div>
        <div class="col text-end"> 
            <%= link_to admin_pedido_path(pedido), class: 'btn btn-secondary text-white' do%>
                <i class="bi bi-search"></i>
            <% end %>
        </div>
    </div>
<% end %>

app/views/admin/pedidos/mostrar.html.erb
<div class="row">
    <div class="col-10">
        <h2>
            PEDIDO <%= @pedido.codigo %> 📦
        </h2>    
    </div>
    <div class="col-2 text-end">
        <%= link_to "Editar", admin_editar_pedido_path(@pedido), class: 'btn btn-success' %>
    </div>
</div>


<div class="row mt-2">
    <div class="col">
        <div class="alert alert-primary" role="alert">
            <%= @pedido.estados_pedido.estado %>
        </div>
    </div>
</div>    

<div class="row mt-1">
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    Datos envío
                </h4>
                <!-- DATOS DE ENVÍO -->
                <div class="row">
                    <div class="col-12">
                        Nombre: <%= @pedido.datos_envio.nombre %>            
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Correo: <%= @pedido.datos_envio.correo %>            
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Teléfono: <%= @pedido.datos_envio.telefono %>            
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Dirección: <%= @pedido.datos_envio.direccion %>
                        
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Ciudad: <%= @pedido.destino.nombre %>                
                    </div>
                </div>
                    
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="row justify-content-end">
            <div class="col-12">
                <div class="card">
                    <div class="card-body text-center">
                        <h6>
                            <strong>
                                TOTAL:
                            </strong>
                        </h6>
                        <p>
                            <%= @pedido.total %>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>


<div class="card mt-3">
    <div class="card-body">
        <h4 class="card-title">
            Productos
        </h4>
        <div class="row  text-center">
            <div class="col-12">
                <div class="row">
                    <div class="col-2">
                        <strong>
                            Imágen
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Nombre
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Precio
                        </strong>
                    </div>
                    <div class="col">
                        <strong>
                            Cantidad
                        </strong>
                    </div>
                </div>
                <% @pedido.detalles_pedidos.each do |detalle| %>
                    <div class="row mt-5">
                        <div class="col-2">
                            <%= image_tag detalle.producto.imagenes.first, class: 'w-100' %>                
                        </div>
                        <div class="col">
                            <%= detalle.producto.nombre %>                
                        </div>
                        <div class="col">
                            <%= detalle.producto.precio %>                
                        </div>
                        <div class="col">
                            <%= detalle.cantidad %>                
                        </div>
                    </div>
                <% end %>
                <!-- MOSTRAR LOS PRODUCTOS -->
            </div>
        </div>
</div>