config/routes.rb
Rails.application.routes.draw do
  # páginas
  root 'paginas#inicio'
  get   '/carrito',     to: 'paginas#carro',              as: 'carrito'
  get   'enviar', to: 'paginas#enviar_saludo'

  # sesiones
  post    '/sesiones',  to: 'sesiones#iniciar_sesion',  as: 'iniciar_sesion'
  delete  '/sesiones',  to: 'sesiones#cerrar_sesion',  as: 'cerrar_sesion'

  # carros
  post    'carros/:id_producto',          to: 'carros#agregar_producto',            as: 'agregar_producto'
  put     'carros/:id_producto/cantidad', to: 'carros#aumentar_cantidad_producto',  as: 'aumentar_producto'
  delete  'carros/:id_producto',          to: 'carros#eliminar_producto',           as: 'eliminar_producto'
  delete  'carros/:id_producto/cantidad', to: 'carros#disminuir_cantidad_producto', as: 'disminuir_producto'

  # pedidos cliente
  get   'pedidos',        to: 'pedidos#crear',    as: 'nuevo_pedido'
  get   'pagar',          to: 'pedidos#pagar',    as: 'pagar'  
  post  'pedidos',        to: 'pedidos#guardar',  as: 'crear_pedido_cliente'

  # admin
  namespace :admin do

    # categorias
    get 'categorias',             to: 'categorias#listar',  as: 'categorias'
    get 'categorias/crear',       to: 'categorias#crear',   as: 'nueva_categoria'
    get 'categorias/:id',         to: 'categorias#mostrar', as: 'categoria'
    get 'categorias/:id/editar',  to: 'categorias#editar',  as: 'editar_categoria'

    post    'categorias',     to: 'categorias#guardar'
    put     'categorias/:id', to: 'categorias#actualizar'
    patch   'categorias/:id', to: 'categorias#actualizar'
    delete  'categorias/:id', to: 'categorias#eliminar'

    # detinos
    get 'destinos',             to: 'destinos#listar',  as: 'destinos'
    get 'destinos/crear',       to: 'destinos#crear',   as: 'nuevo_destino'
    get 'destinos/:id',         to: 'destinos#mostrar', as: 'destino'
    get 'destinos/:id/editar',  to: 'destinos#editar',  as: 'editar_destino'

    post    'destinos',     to: 'destinos#guardar'
    put     'destinos/:id', to: 'destinos#actualizar'
    patch   'destinos/:id', to: 'destinos#actualizar'
    delete  'destinos/:id', to: 'destinos#eliminar'

    # productos
    get 'productos',              to: 'productos#listar',   as: 'productos'
    get 'productos/crear',        to: 'productos#crear',    as: 'nuevo_producto'
    get 'productos/:id',          to: 'productos#mostrar',  as: 'producto'
    get 'productos/:id/editar',   to: 'productos#editar',   as: 'editar_producto'

    post    'productos',                          to: 'productos#guardar'
    put     'productos/:id',                      to: 'productos#actualizar'
    patch   'productos/:id',                      to: 'productos#actualizar'
    # delete  'productos/:id',                      to: 'productos#eliminar'
    
    delete  'productos/:id/imagenes/:id_imagen',  to: 'productos#eliminar_foto',  as: 'eliminar_foto'

    # pedidos
    get '/',                  to: 'pedidos#listar',   as: 'pedidos'
    # get 'pedidos/crear',      to: 'pedidos#crear',    as: 'nuevo_pedido'
    get 'pedidos/:id',        to: 'pedidos#mostrar',  as: 'pedido'
    get 'pedidos/:id/editar', to: 'pedidos#editar',   as: 'editar_pedido'

    post    'pedidos',      to: 'pedidos#crear',      as: 'pedidos_helper_pedidos_formularios'
    put     'pedidos/:id',  to: 'pedidos#actualizar'
    patch   'pedidos/:id',  to: 'pedidos#actualizar', as: 'pedidos_helper_pedidos_formulario'
    delete  'pedidos/:id',  to: 'pedidos#eliminar'

    get     'pedidos/:id/productos',                        to: 'pedidos#agregar_producto',             as: 'agregar_producto_pedido'
    post    'pedidos/:id/productos/:id_producto',           to: 'pedidos#guardar_producto',             as: 'guardar_producto_pedido'
    put     'pedidos/:id/productos/:id_producto',           to: 'pedidos#aumentar_cantidad_producto',   as: 'aumentar_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto',           to: 'pedidos#disminuir_cantidad_producto',  as: 'disminuir_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto/eliminar',  to: 'pedidos#eliminar_producto',            as: 'eliminar_producto_pedido'
  end
end

app/models/destino.rb
class Destino < ApplicationRecord
  belongs_to :region
  has_many :pedidos

  validates(:nombre, presence: true)
  validates(:region_id, presence: true)
  
end

app/controllers/admin/destinos_controller.rb
class Admin::DestinosController < Admin::AdminController
    before_action :asignar_destino, only: [:mostrar, :editar, :actualizar, :eliminar]
    # GET
    def listar
        @destinos = Destino.includes(:region).select(:id, :nombre, :region_id)
    end

    # GET
    def mostrar        
        
    end
    
    # GET
    def crear
        @destino = Destino.new
        consultar_regiones
    end

    # GET
    def editar
        consultar_regiones
    end

    # POST
    def guardar
        @destino = Destino.new(params_destino)
        if @destino.save
            redirect_to action: :listar
        else
            consultar_regiones
            render :crear
        end
    end

    # PUT/PATCH
    def actualizar
        if @destino.update(params_destino)
            redirect_to action: :listar
        else
            consultar_regiones
            render :editar
        end
    end

    # DELETE
    def eliminar
        @destino.destroy
        redirect_to action: :listar
    end

    private
    def asignar_destino
        @destino = Destino.find(params[:id])
    end

    def params_destino
        params.require(:destino).permit(:nombre, :region_id)
    end

    def consultar_regiones
        @regiones = Region.select(:id, :nombre).order(id: :asc)
    end
end

app/views/admin/destinos/_formulario.html.erb
<div class="row">
    <div class="col-6 contenedor-formulario">
        <%= form_with(model: [:admin, destino]) do |f| %>

            <div class="mb-3">    
                <%= f.label :nombre, class: 'form-label' %>
                <%= f.text_field :nombre, class: 'form-control' %>
                <% if destino.errors[:nombre].any? %>
                    <div style="color: red;">
                        <%= destino.errors[:nombre].first %>
                    </div>
                <% end %>
            </div>

            <div class="mb-3">
                <%= f.label :region_id, class: 'form-label' %>
                <% if destino.region %>
                    <%= f.select(:region_id,
                        options_from_collection_for_select(regiones, :id, :nombre, destino.region_id),
                        {include_blank: 'Elige una region'},
                        {class: 'form-select'}) %>
                <% else %>
                    <%= f.select(:region_id,
                        options_from_collection_for_select(regiones, :id, :nombre),
                        {include_blank: 'Elige una region'},
                        {class: 'form-select'}) %>
                <% end %>
                
                <% if destino.errors[:region_id].any? %>
                    <div style="color: red;">
                        <%= destino.errors[:region_id].first %>
                    </div>
                <% end %>
            </div>
            
            <%= f.submit class: 'btn btn-primary' do %>

            <% end %>
            
        <% end %>

    </div>
</div>

app/views/admin/destinos/crear.html.erb
<h1 class="titulo-formulario">Registrar destino</h1>

<%= render 'formulario', 
    destino: @destino, 
    regiones: @regiones  %>

app/views/admin/destinos/editar.html.erb
<h1 class="titulo-formulario">Editar destino</h1>

<%= render 'formulario', 
    destino: @destino, 
    regiones: @regiones  %>

app/views/admin/destinos/listar.html.erb
<h1 class="titulo-seccion">Destinos</h1>

<%= link_to admin_nuevo_destino_path, class: "btn btn-primary text-white boton-crear-derecha" do %>
    <i class="bi bi-plus-circle"></i>
    Crear destino
<% end %>

<div class="tabla-categorias">
    <div class="row justify-content-between">
        <div class="col-4">
            <h4>Nombre</h4>
        </div>
        <div class="col-4">
            <h4>Región</h4>
        </div>
        <div class="col-4">
            <h4>Opciones</h4>
        </div>
    </div>

    <% @destinos.each do |destino| %>
        <div class="row justify-content-between fila">
            <div class="col-4"><%= destino.nombre %></div>
            <div class="col-4"><%= destino.region.nombre %></div>
            <div  class="col-4">
                <%= link_to admin_editar_destino_path(destino), class: "btn btn-warning boton-editar" do %>
                    <i class="bi bi-pencil-fill"></i> 
                <% end %>
                <%= link_to admin_destino_path(destino), method: :delete, data: { confirm: '¿Quieres eliminar la destino?' }, class: "btn btn-danger" do %>                   
                        <i class="bi bi-trash-fill"></i> 
                <% end %>
            </div>
        </div>
    <% end %>
</div>