config/routes.rb
Rails.application.routes.draw do
  # páginas
  root 'paginas#inicio'
  get   '/carrito',     to: 'paginas#carro',              as: 'carrito'
  get   'enviar', to: 'paginas#enviar_saludo'

  # sesiones
  post    '/sesiones',  to: 'sesiones#iniciar_sesion',  as: 'iniciar_sesion'
  delete  '/sesiones',  to: 'sesiones#cerrar_sesion',  as: 'cerrar_sesion'

  # carros
  post    'carros/:id_producto',          to: 'carros#agregar_producto',            as: 'agregar_producto'
  put     'carros/:id_producto/cantidad', to: 'carros#aumentar_cantidad_producto',  as: 'aumentar_producto'
  delete  'carros/:id_producto',          to: 'carros#eliminar_producto',           as: 'eliminar_producto'
  delete  'carros/:id_producto/cantidad', to: 'carros#disminuir_cantidad_producto', as: 'disminuir_producto'

  # pedidos cliente
  get   'pedidos',        to: 'pedidos#crear',    as: 'nuevo_pedido'
  get   'pagar',          to: 'pedidos#pagar',    as: 'pagar'  
  post  'pedidos',        to: 'pedidos#guardar',  as: 'crear_pedido_cliente'

  # admin
  namespace :admin do

    # categorias
    get 'categorias',             to: 'categorias#listar',  as: 'categorias'
    get 'categorias/crear',       to: 'categorias#crear',   as: 'nueva_categoria'
    get 'categorias/:id',         to: 'categorias#mostrar', as: 'categoria'
    get 'categorias/:id/editar',  to: 'categorias#editar',  as: 'editar_categoria'

    post    'categorias',     to: 'categorias#guardar'
    put     'categorias/:id', to: 'categorias#actualizar'
    patch   'categorias/:id', to: 'categorias#actualizar'
    delete  'categorias/:id', to: 'categorias#eliminar'

    # detinos
    get 'destinos',             to: 'destinos#listar',  as: 'destinos'
    get 'destinos/crear',       to: 'destinos#crear',   as: 'nuevo_destino'
    get 'destinos/:id',         to: 'destinos#mostrar', as: 'destino'
    get 'destinos/:id/editar',  to: 'destinos#editar',  as: 'editar_destino'

    post    'destinos',     to: 'destinos#guardar'
    put     'destinos/:id', to: 'destinos#actualizar'
    patch   'destinos/:id', to: 'destinos#actualizar'
    delete  'destinos/:id', to: 'destinos#eliminar'

    # productos
    get 'productos',              to: 'productos#listar',   as: 'productos'
    get 'productos/crear',        to: 'productos#crear',    as: 'nuevo_producto'
    get 'productos/:id',          to: 'productos#mostrar',  as: 'producto'
    get 'productos/:id/editar',   to: 'productos#editar',   as: 'editar_producto'

    post    'productos',                          to: 'productos#guardar'
    put     'productos/:id',                      to: 'productos#actualizar'
    patch   'productos/:id',                      to: 'productos#actualizar'
    # delete  'productos/:id',                      to: 'productos#eliminar'
    
    delete  'productos/:id/imagenes/:id_imagen',  to: 'productos#eliminar_foto',  as: 'eliminar_foto'

    # pedidos
    get '/',                  to: 'pedidos#listar',   as: 'pedidos'
    # get 'pedidos/crear',      to: 'pedidos#crear',    as: 'nuevo_pedido'
    get 'pedidos/:id',        to: 'pedidos#mostrar',  as: 'pedido'
    get 'pedidos/:id/editar', to: 'pedidos#editar',   as: 'editar_pedido'

    post    'pedidos',      to: 'pedidos#crear',      as: 'pedidos_helper_pedidos_formularios'
    put     'pedidos/:id',  to: 'pedidos#actualizar'
    patch   'pedidos/:id',  to: 'pedidos#actualizar', as: 'pedidos_helper_pedidos_formulario'
    delete  'pedidos/:id',  to: 'pedidos#eliminar'

    get     'pedidos/:id/productos',                        to: 'pedidos#agregar_producto',             as: 'agregar_producto_pedido'
    post    'pedidos/:id/productos/:id_producto',           to: 'pedidos#guardar_producto',             as: 'guardar_producto_pedido'
    put     'pedidos/:id/productos/:id_producto',           to: 'pedidos#aumentar_cantidad_producto',   as: 'aumentar_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto',           to: 'pedidos#disminuir_cantidad_producto',  as: 'disminuir_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto/eliminar',  to: 'pedidos#eliminar_producto',            as: 'eliminar_producto_pedido'
  end
end

app/models/categoria.rb
class Categoria < ApplicationRecord
    has_many :productos
    validates(:categoria, uniqueness: true)
    validates(:categoria, presence: true)
end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::AdminController

    before_action :asignar_categoria, only: %i(mostrar, editar, actualizar, eliminar)
    # GET
    def listar
        @categorias = Categoria.select(:id, :categoria).order(categoria: :asc)
    end

    # GET
    def mostrar
        
    end
    
    # GET
    def crear
        @categoria = Categoria.new
    end

    # GET
    def editar

    end

    # POST
    def guardar
        @categoria = Categoria.new(params_categoria)
        if @categoria.save
            redirect_to action: :listar
        else
            render :crear
        end
    end

    # PUT/PATCH
    def actualizar
        if @categoria.update(params_categoria)
            redirect_to action: :listar
        else
            render :editar
        end
    end

    # DELETE
    def eliminar
        @categoria.destroy
        redirect_to action: :listar
    end

    private
    def asignar_categoria
        @categoria = Categoria.find(params[:id])
    end

    def params_categoria
        params.require(:categoria).permit(:categoria)
    end

end

app/views/admin/categorias/_formulario.html.erb
<div class="row">
    <div class="col-6 contenedor-formulario">

        <%= form_with(model: [:admin, categoria]) do |formulario| %>
            <div class="mb-3">
                <%= formulario.label :categoria, 'Nombre', class: "form-label" %>
                <%= formulario.text_field :categoria, autofocus: 'autofocus', class: "form-control" %>
                <% if categoria.errors[:categoria].any? %>
                    <%= categoria.errors[:categoria].first %>
                <% end %>
            </div>

            <%= formulario.submit(class: 'btn btn-primary')  do %>

            <% end %>

        <% end %>
    </div>
</div>

app/views/admin/categorias/crear.html.erb
<h2 class="titulo-formulario">Crear categoría</h2>

<%= render 'formulario', categoria: @categoria %>

app/views/admin/categorias/editar.html.erb
<h1>Editar categoria</h1>

<%= render 'formulario', categoria: @categoria %>

app/views/admin/categorias/listar.html.erb
<h1 class="titulo-seccion">Categorias</h1>

<%= link_to admin_nueva_categoria_path, class: "btn btn-primary text-white boton-crear-derecha" do %>
    <i class="bi bi-plus-circle"></i>
    Crear categoría
<% end %>

<div class="tabla-categorias">
    <div class="row justify-content-between">
        <div class="col-4">
            <h4>Nombre</h4>
        </div>
        <div class="col-4">
            <h4>Opciones</h4>
        </div>
    </div>

    <% @categorias.each do |categoria| %>
        <div class="row justify-content-between fila">
            <div class="col-4"><%= categoria.categoria %></div>
            <div  class="col-4">
                <%= link_to admin_editar_categoria_path(categoria), class: "btn btn-warning boton-editar" do %>
                    <i class="bi bi-pencil-fill"></i> 
                <% end %>
                <%= link_to admin_categoria_path(categoria), method: :delete, data: { confirm: '¿Quieres eliminar la categoria?' }, class: "btn btn-danger" do %>                   
                        <i class="bi bi-trash-fill"></i> 
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/categorias/mostrar.html.erb
<%= @categoria.categoria %>

<%= link_to 'Ver categorias', categorias_path %>