config/routes.rb
Rails.application.routes.draw do
  # páginas
  root 'paginas#inicio'
  get   '/carrito',     to: 'paginas#carro',              as: 'carrito'
  get   'enviar', to: 'paginas#enviar_saludo'

  # sesiones
  post    '/sesiones',  to: 'sesiones#iniciar_sesion',  as: 'iniciar_sesion'
  delete  '/sesiones',  to: 'sesiones#cerrar_sesion',  as: 'cerrar_sesion'

  # carros
  post    'carros/:id_producto',          to: 'carros#agregar_producto',            as: 'agregar_producto'
  put     'carros/:id_producto/cantidad', to: 'carros#aumentar_cantidad_producto',  as: 'aumentar_producto'
  delete  'carros/:id_producto',          to: 'carros#eliminar_producto',           as: 'eliminar_producto'
  delete  'carros/:id_producto/cantidad', to: 'carros#disminuir_cantidad_producto', as: 'disminuir_producto'

  # pedidos cliente
  get   'pedidos',        to: 'pedidos#crear',    as: 'nuevo_pedido'
  get   'pagar',          to: 'pedidos#pagar',    as: 'pagar'  
  post  'pedidos',        to: 'pedidos#guardar',  as: 'crear_pedido_cliente'

  # admin
  namespace :admin do

    # categorias
    get 'categorias',             to: 'categorias#listar',  as: 'categorias'
    get 'categorias/crear',       to: 'categorias#crear',   as: 'nueva_categoria'
    get 'categorias/:id',         to: 'categorias#mostrar', as: 'categoria'
    get 'categorias/:id/editar',  to: 'categorias#editar',  as: 'editar_categoria'

    post    'categorias',     to: 'categorias#guardar'
    put     'categorias/:id', to: 'categorias#actualizar'
    patch   'categorias/:id', to: 'categorias#actualizar'
    delete  'categorias/:id', to: 'categorias#eliminar'

    # detinos
    get 'destinos',             to: 'destinos#listar',  as: 'destinos'
    get 'destinos/crear',       to: 'destinos#crear',   as: 'nuevo_destino'
    get 'destinos/:id',         to: 'destinos#mostrar', as: 'destino'
    get 'destinos/:id/editar',  to: 'destinos#editar',  as: 'editar_destino'

    post    'destinos',     to: 'destinos#guardar'
    put     'destinos/:id', to: 'destinos#actualizar'
    patch   'destinos/:id', to: 'destinos#actualizar'
    delete  'destinos/:id', to: 'destinos#eliminar'

    # productos
    get 'productos',              to: 'productos#listar',   as: 'productos'
    get 'productos/crear',        to: 'productos#crear',    as: 'nuevo_producto'
    get 'productos/:id',          to: 'productos#mostrar',  as: 'producto'
    get 'productos/:id/editar',   to: 'productos#editar',   as: 'editar_producto'

    post    'productos',                          to: 'productos#guardar'
    put     'productos/:id',                      to: 'productos#actualizar'
    patch   'productos/:id',                      to: 'productos#actualizar'
    # delete  'productos/:id',                      to: 'productos#eliminar'
    
    delete  'productos/:id/imagenes/:id_imagen',  to: 'productos#eliminar_foto',  as: 'eliminar_foto'

    # pedidos
    get '/',                  to: 'pedidos#listar',   as: 'pedidos'
    # get 'pedidos/crear',      to: 'pedidos#crear',    as: 'nuevo_pedido'
    get 'pedidos/:id',        to: 'pedidos#mostrar',  as: 'pedido'
    get 'pedidos/:id/editar', to: 'pedidos#editar',   as: 'editar_pedido'

    post    'pedidos',      to: 'pedidos#crear',      as: 'pedidos_helper_pedidos_formularios'
    put     'pedidos/:id',  to: 'pedidos#actualizar'
    patch   'pedidos/:id',  to: 'pedidos#actualizar', as: 'pedidos_helper_pedidos_formulario'
    delete  'pedidos/:id',  to: 'pedidos#eliminar'

    get     'pedidos/:id/productos',                        to: 'pedidos#agregar_producto',             as: 'agregar_producto_pedido'
    post    'pedidos/:id/productos/:id_producto',           to: 'pedidos#guardar_producto',             as: 'guardar_producto_pedido'
    put     'pedidos/:id/productos/:id_producto',           to: 'pedidos#aumentar_cantidad_producto',   as: 'aumentar_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto',           to: 'pedidos#disminuir_cantidad_producto',  as: 'disminuir_producto_pedido'
    delete  'pedidos/:id/productos/:id_producto/eliminar',  to: 'pedidos#eliminar_producto',            as: 'eliminar_producto_pedido'
  end
end

app/views/layouts/_navbar.html.erb
<nav id="navegacion" class="navbar navbar-expand-lg fixed-top bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="/admin">
            <i class="bi bi-joystick"></i>
            Game Store
        </a>
        <button class="navbar-toggler boton-navbar-hamburguesa" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon icono-navbar-hamburguesa"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to admin_pedidos_path, class: 'nav-link'  do %>
                        <i class="bi bi-speedometer"></i>
                        Pedidos
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to admin_productos_path, class: 'nav-link'  do %>
                        <i class="bi bi-archive-fill"></i>
                        Productos
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to admin_categorias_path, class: 'nav-link'  do %>                    
                        <i class="bi bi-bookmark-fill"></i>
                        Categorías
                    <% end %>
                </li>

                <li class="nav-item">
                    <%= link_to admin_destinos_path, class: 'nav-link'  do %>
                        <i class="bi bi-compass-fill"></i>
                        Destinos
                    <% end %>
                </li>

                <li class="nav-item">
                    <% if usuario_ha_iniciado_sesion? %>

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= @usuario_actual.nombre %>
                        </a><!-- Opción para mostrar el formulario ⏬ -->
                        <div class="dropdown-menu bg-secondary p-3" style="border: none;">
                            <%= link_to 'Cerrar sesión', cerrar_sesion_path, class: 'btn btn-warning', method: :delete, data: { confirm: 'está seguro de cerrar sesión?'} %>
                        </div>

                    <% end %>
                </li>
                
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_navbar_cliente.html.erb
<nav id="navegacion" class="navbar navbar-expand-lg bg-secondary fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <i class="bi bi-shop"></i>
            Carrito
        </a>
        <button class="navbar-toggler boton-navbar-hamburguesa" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon icono-navbar-hamburguesa"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">
                        <i class="bi bi-house-door"></i>
                        Inicio
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/carrito">
                        <i class="bi bi-cart-fill"></i>
                        Carrito <span class="badge bg-danger"><%= @carro.carros_contenidos.map{ |p| p.cantidad }.sum %> </span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    
                    <% if usuario_ha_iniciado_sesion? %>

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= @usuario_actual.nombre %>
                        </a><!-- Opción para mostrar el formulario ⏬ -->
                        <div class="dropdown-menu bg-secondary p-3" style="border: none;">
                            <%= link_to 'Cerrar sesión', cerrar_sesion_path, class: 'btn btn-warning', method: :delete, data: { confirm: 'está seguro de cerrar sesión?'} %>
                        </div>

                    <% else %>                   

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Iniciar sesión
                        </a><!-- Opción para mostrar el formulario ⏬ -->

                        <div class="dropdown-menu">
                            <%= form_with(url: iniciar_sesion_path, class: 'p-4') do |formulario| %>
                                <div class="mb-3">
                                    <%= formulario.label :correo, class: 'form-label' %>
                                    <%= formulario.text_field :correo, class: 'form-control', placeholder: 'nombre@ejemplo.com' %>
                                </div>
                                <div class="mb-3">
                                    <%= formulario.label :password, class: 'form-label' %>
                                    <%= formulario.password_field :password, class: 'form-control' %>
                                </div>

                                <%= formulario.submit 'Iniciar sesión', class: 'btn' %>
                            <% end %>
                        </div>

                    <% end %>

                </li>
            </ul>
        </div>
        
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>    
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container contenedor">
      <%= yield %>    
    </div>

    <!-- Javascript Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/paginas.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Carrito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/navbar_cliente' %>


    <div class="container contenedor">

        <% if flash[:error_sesion] %>
            <div class="alert alert-danger" role="alert">
                <%= flash[:error_sesion] %>
            </div>
        <% end %>

        <%= yield %>    
    </div> <!-- Contenedor yield 📦 -->

    <!-- Javascript Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
</body>
</html>